# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22767b2bc8365226cec3b50b263f5f04e654fa452d9fc1b7f36fcdc55f9f2e2c464557a3ca81436ed40af58bc3e8d9a68eedf210ac2c79e16fee0aec4640ed48

test:
  secret_key_base: b590149306a729febdff899e7d4eab398dfe9508324e1390ff5525001515eb839b20f7f7bd746457d40b627f36b0f5adc27ad1f8638cbeb0533a5ce785e838fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
